# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7414421fee38fd84f5af8c3c9498e7f3929b2287f94b8c0f402de29be450ebc551faa3a76f809da25dad225956ded5bcb52b4537c7285debee1d901613146469

test:
  secret_key_base: 6d0a1155aa3eb73abafb187072a7225e17f7ebde07d6936c82e7112c57008c427c94c2e81ec0d966e999cc5166e9ae1de122c4322a31d144de9ce13bfe105c20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
